language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zielin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zielin/docker-react npm run start

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-730448988297"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"